CREATE TABLE things(Id int Primary key)
GO

CREATE TABLE 
Books(Bid INT PRIMARY KEY, Tid INT FOREIGN KEY REFERENCES things(Id) )
GO

CREATE TABLE thing1(Id int Primary key check (Id>100))

CREATE TABLE thing2(Id int , Dt DATETIME DEFAULT GETDATE())

CREATE INDEX index_Id
ON things(Id)


DROP TABLE Books
DROP TABLE things

SET STATISTICS TIME ON;
SET STATISTICS IO ON;
GO


SELECT DATEDIFF(hh,DATEPART(DD,EOMONTH(GETDATE())),EOMONTH(GETDATE()))

Go


SELECT DATEPART(M,GETDATE())
SELECT DATEPART(DD,EOMONTH(GETDATE()))

SELECT *  FROM THINGS

--FUNCTIONS, STORED PROCESDURES, TRIGGERS, CURSORS, MERGE
--FUNCTIONS--
CREATE OR ALTER FUNCTION Fn_things(@id int)
RETURNS FLOAT
as
BEGIN
	DECLARE @avg int 
	SELECT @avg=AVG(id) 
	FROM things
	WHERE ID=@id
	RETURN @avg
END

-------STORED PROCESDURES--------------


select @@version

